
services:

  db:
     image: mariadb:12.3.2
     container_name: dis_db
     restart: unless-stopped
     healthcheck:
      test: ["CMD", "healthcheck.sh","--su-mysql", "--connect", "--innodb_initialized"]
      interval: 5s
      timeout: 5s
      retries: 10
     environment:
     #ESCONDER CONTRASEÑAS FINALES EN UN .ENV
      MYSQL_ROOT_PASSWORD: root_password_super_secret
      MYSQL_DATABASE: DISNUTZTEST01
      MYSQL_USER: user_app
      MYSQL_PASSWORD: secure_password
     volumes:
      - mariadb_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
     networks:
      - dis_private_network

  backend:
    build:
      context: .
      dockerfile: ./Controller/Dockerfile
    container_name: dis_backend
    restart: unless-stopped
     
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/Controller/node_modules
      - /app/View/frontend/node_modules
      - /app/Model/node_modules
      - /app/Db/node_modules
    environment:
      - PORT=3000
      - JWT_SECRET=We Love each Other
      - CHOKIDAR_USEPOLLING=true  
      - WATCHPACK_POLLING=true
    depends_on:
        db:
          condition: service_healthy
    networks:
      - dis_private_network
      - dis_public_network

  frontend:
    build:
      context: .
      dockerfile:  ./View/frontend/Dockerfile
    container_name: dis-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
      - /app/Controller/node_modules
      - /app/View/frontend/node_modules
      - /app/Model/node_modules
      - /app/Db/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
    networks:
      - dis_public_network

volumes:
  mariadb_data:

networks:
  dis_private_network:
    driver: bridge
  dis_public_network:
    driver: bridge
